### ISSUE TITLE
OpenID 2.0 is no more supported by Google.

### ISSUE THREAD

**Issue by pradeeban** [sharmalab/bindaas#20]
See - https://developers.google.com/identity/protocols/OpenID2

Therefore, when you choose Query Browser > Google, empty page shows up, with the below logs in the console.

osgi>28 Jun 2018 16:59:39,054 ERROR openid.OpenIDHelper - Error redirecting to OpenID provider
org.openid4java.discovery.yadis.YadisException: 0x706: GET failed on https://www.google.com/accounts/o8/id : 404
	at org.openid4java.discovery.yadis.YadisResolver.retrieveXrdsLocation(YadisResolver.java:411)
	at org.openid4java.discovery.yadis.YadisResolver.discover(YadisResolver.java:252)
	at org.openid4java.discovery.yadis.YadisResolver.discover(YadisResolver.java:232)
	at org.openid4java.discovery.yadis.YadisResolver.discover(YadisResolver.java:166)
	at org.openid4java.discovery.Discovery.discover(Discovery.java:147)
	at org.openid4java.discovery.Discovery.discover(Discovery.java:129)
	at org.openid4java.consumer.ConsumerManager.discover(ConsumerManager.java:538)
	at edu.emory.cci.bindaas.openid.OpenIDHelper.authRequest(OpenIDHelper.java:83)
	at edu.emory.cci.bindaas.webconsole.servlet.usermgmt.UserOpenIDAuthServlet.doPost(UserOpenIDAuthServlet.java:53)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:595)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.apache.felix.http.base.internal.handler.ServletHandler.doHandle(ServletHandler.java:96)
	at org.apache.felix.http.base.internal.handler.ServletHandler.handle(ServletHandler.java:79)
	at org.apache.felix.http.base.internal.dispatch.ServletPipeline.handle(ServletPipeline.java:42)
	at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:49)
	at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
	at org.apache.felix.http.base.internal.handler.FilterHandler.handle(FilterHandler.java:78)
	at org.apache.felix.http.base.internal.dispatch.InvocationFilterChain.doFilter(InvocationFilterChain.java:47)
	at org.apache.felix.http.base.internal.dispatch.HttpFilterChain.doFilter(HttpFilterChain.java:33)
	at org.apache.felix.http.base.internal.dispatch.FilterPipeline.dispatch(FilterPipeline.java:48)
	at org.apache.felix.http.base.internal.dispatch.Dispatcher.dispatch(Dispatcher.java:39)
	at org.apache.felix.http.base.internal.DispatcherServlet.service(DispatcherServlet.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:668)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:511)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:390)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:182)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:765)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
	at org.mortbay.jetty.Server.handle(Server.java:326)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:542)
	at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:926)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:549)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:212)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:404)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:410)
	at org.mortbay.thread.QueuedThreadPool$PoolThread.run(QueuedThreadPool.java:582)

**Comment by pradeeban** [comment]
We are giving up both Google and Yahoo OpenID.
